# Generated by Django 2.1.7 on 2019-05-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('speed', models.IntegerField()),
                ('target_temper', models.IntegerField()),
                ('room_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'RequestMM',
            },
        ),
        migrations.CreateModel(
            name='RoomStatusDao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('target_temper', models.FloatField()),
                ('current_temper', models.FloatField()),
                ('speed', models.IntegerField()),
                ('Fee', models.FloatField()),
                ('time', models.FloatField()),
                ('is_log', models.BooleanField()),
            ],
            options={
                'db_table': 'Room',
            },
        ),
    ]
