# Generated by Django 2.1.7 on 2019-05-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmachine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstatusdao',
            name='Fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='roomstatusdao',
            name='current_temper',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='roomstatusdao',
            name='is_log',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='roomstatusdao',
            name='speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roomstatusdao',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roomstatusdao',
            name='target_temper',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='roomstatusdao',
            name='time',
            field=models.FloatField(null=True),
        ),
    ]
