# Generated by Django 2.1.7 on 2019-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmachine', '0002_auto_20190520_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomstatusdao',
            old_name='Fee',
            new_name='fee',
        ),
        migrations.RemoveField(
            model_name='roomstatusdao',
            name='is_log',
        ),
        migrations.AddField(
            model_name='roomstatusdao',
            name='fee_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='roomstatusdao',
            name='mode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='roomstatusdao',
            name='service_time',
            field=models.FloatField(null=True),
        ),
    ]
