# Generated by Django 2.1.7 on 2019-05-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmachine', '0003_auto_20190523_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstatusdao',
            name='fee',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='roomstatusdao',
            name='service_time',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
