# Generated by Django 2.1.7 on 2019-05-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currenttime', models.DateTimeField()),
                ('userid', models.CharField(max_length=10)),
                ('roomid', models.CharField(max_length=2)),
                ('temperature', models.FloatField()),
                ('windspeed', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
